import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Toaster } from 'react-hot-toast';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Toaster
          position="top-right"
          toastOptions={{
            className: '',
            style: {
              border: '3px solid black',
              borderRadius: '0px',
              boxShadow: '4px 4px 0px black',
              color: '#000',
              background: '#fff',
              fontWeight: 'bold',
            },
            success: {
              style: {
                background: '#dcfce7', // green-100
              },
              iconTheme: {
                primary: 'black',
                secondary: '#4ade80',
              },
            },
            error: {
              style: {
                background: '#fee2e2', // red-100
              },
              iconTheme: {
                primary: 'black',
                secondary: '#f87171',
              }
            }
          }}
        />
        {children}
      </body>
    </html>
  );
}
